services:
    client:
        user: node
        image: node:18-alpine
        command: ["npm", "run", "dev"]
        working_dir: /home/node/client
        ports:
            - "3000:3000"
        volumes:
            - ${PWD}/client:/home/node/client
            - ${PWD}/shared:/home/node/shared